# Dependencies
markdown:           kramdown
highlighter:        rouge
excerpt_separator:  "<!--more-->"
kramdown:
  parse_block_html: true

# Permalinks
permalink:         /blog/:year/:month/:day/:title/

# Setup
title:             Terence Z. Liu
tagline:           "ML / Data / Platform<br>Ph.D."

name:              Terence Z. Liu
email:             terence.z.liu@gmail.com
linkedin_username: terence-z-liu
github_username:   terencezl
twitter_username:  "@terencezliu"

url:               https://terencezl.github.io
baseurl:           ''

paginate:          100
paginate_path:     blog/page:num

# Plugins
plugins:           [jekyll-paginate, jekyll-gist]
