# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ['strikethrough']

# Permalinks
permalink:        /blog/:year/:month/:day/:title/
relative_permalinks: true

# Setup
title:            Terence
description:      'His research site.'
url:              http://terencezl.github.io
baseurl:          /

author:
  name:           'Terence Zhi Liu'
  url:            http://terencezl.github.io

paginate:         5
paginate_path: "blog/page:num"