# Site settings
title: Terence
description: >
  His research site.
name: Terence Zhi Liu
email: terencelz90@gmail.com
email_md5: a40ee9e9ce8a2bbd3c4a0d34962c83e2
twitter_username: terencezlew
github_username:  terencezl
linkedin_username: terence-zhi-liu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://terencezl.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
paginate: 10 # pagination based on number of posts
paginate_path: "blog/page:num"
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: "/blog/:title/"
