# Dependencies
markdown:         kramdown
highlighter:      rouge
excerpt_separator: "<!--more-->"

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            Terence's Site
#description:      Research site, mainly.

name: Terence Zhi Liu
email: terencelz90@gmail.com
linkedin_username: terence-zhi-liu-3353b142
github_username:  terencezl

url:              http://terencezl.github.io
baseurl:          ''

paginate:         5
paginate_path:    blog/page:num

# Plugins
gems: ['jekyll-paginate']
