# Dependencies
markdown:         kramdown
highlighter:      rouge
excerpt_separator: "<!--more-->"

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            Terence's Site

name: Terence Zhi Liu
email: terence.z.liu@gmail.com
github_username:  terencezl

url:              http://terencezl.github.io
baseurl:          ''

paginate:         5
paginate_path:    blog/page:num

# Plugins
gems: ['jekyll-paginate']
